version: "3.1"
services:
    db:
        image: postgres:12
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
            POSTGRES_DB: postgres
        volumes:
            - c:\docker\odoopython\odoo-db:/var/lib/postgresql/data
        networks:
            - default
        ports:
            - 5442:5432
    web:
        image: odoo:14
        links:
            - db:db
        ports:
            - 8072:8069
        volumes:
            - c:\docker\odoopython\odoo-data:/var/lib/odoo
            - c:\docker\odoopython\addons:/mnt/extra-addons
            - c:\docker\odoopython\config:/etc/odoo
        entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf -u practicasfct"